---
- name: RHV VM deployment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml

  vars:
    engine_url: https://rhevm.chen.com/ovirt-engine/api
    engine_user: admin@internal
    engine_cafile: rhv_ca.pem
    datacenter: Default
    cluster: Default

  pre_tasks:
    - name: Login to rhv
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  tasks:
  - name: deploying a RHV VM
    ovirt_vms:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: rhel7u4_base
      cluster: "{{ cluster }}"
      cloud_init:
        user_name: root
        root_password: 'eddiechen'
        custom_script: |
          runcmd:
          - /usr/bin/hostnamectl set-hostname {{ vm_name }}.chen.com

  post_tasks:
    - name: Logout from rhv
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
