---
- hosts: labservers
  remote_user: root

  tasks:
  - name: add resolv.conf file
    template: src=/srv/resolv.conf dest=/etc/resolv.conf
  
  - name: add motd file
    template: src=/srv/motd dest=/etc/motd

  - name: install the latest oscap utilities
    yum: name=openscap-utils state=latest
    yum: name=scap-security-guide state=latest

  - name: install the latest ntp rpm
    yum: name=ntp state=latest
  - name: write the ntp config file
    template: src=/srv/ntp.conf dest=/etc/ntp.conf
    notify: 
    - restart ntpd
  - name: ensure ntp is running (and enable it at boot)
    service: name=ntpd state=started enabled=yes
  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted
