---
- name: loading variables
  include_vars: "vault_vars.yml"

- name: Re-register server with AD through VAS
  command: /opt/quest/bin/vastool -u "{{ vas_username }}" -w "{{ vas_password }}' join -f -n {{inventory_hostname}} GENWORTH.NET | tee /var/tmp/VASinstall/join-{{inventory_hostname}}.log
  ignore_errors: false
