---
- hosts: labservers
  remote_user: root

  tasks:
  - name: install the latest oscap utilities
    yum: pkg={{item}} state=installed
    with_items:
      - openscap
      - openscap-utils
      - scap-security-guide
    ignore_errors: true

  - name: create OSCAP remediation script
    command: /usr/bin/oscap xccdf generate fix --template urn:xccdf:fix:script:sh --profile xccdf_org.ssgproject.content_profile_common --output /tmp/remediation-script.sh /usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml

  - name: remediate server from OSCAP audit
    command: /bin/sh /tmp/remediation-script.sh

  - name: clean up and delete remediation script
    command: /bin/rm /tmp/remediation-script.sh

  - name: validate remediation script
    command: /usr/bin/oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_common --results /tmp/results.xml /usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml
    no_log: True
