---
- hosts: all
  remote_user: root

  tasks:
  - name: enable Red Hat repos
    command: /usr/sbin/subscription-manager repos --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-7-server-extras-rpms
    ignore_errors: True

  - name: install necessary RPM packages
    yum:
      state: latest
      name: "{{ item }}"
    with_items:
      - unzip
      - wget

  - name: download the latest ansible tower
    get_url:
      url: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
      dest: /tmp/ansible-tower-setup-bundle-latest.el7.tar.gz

  - name: create directory /tmp/ansible-tower-setup-bundle-latest
    file:
      path: /tmp/ansible-tower-setup-bundle-latest
      state: directory
      mode: 0755

  - name: unzip ansible tower bundle
    command: tar -zxvf /tmp/ansible-tower-setup-bundle-latest.el7.tar.gz -C /tmp/ansible-tower-setup-bundle-latest/ --strip-components=1

  - name: modify inventory file
    template:
      src: /opt/ansible_playbooks/inventory
      dest: /tmp/ansible-tower-setup-bundle-latest/inventory

  - name: run tower installation
    command: sh /tmp/ansible-tower-setup-bundle-latest/setup.sh -i /tmp/ansible-tower-setup-bundle-latest/inventory
