---
- hosts: all

  tasks:
  - name: installing ntp
    yum:
      name: ntp
      state: latest
  - name: ensure ntp is running
    service:
      name: ntpd
      state: started
  handlers:
    - name: if ntp is not running
      service:
        name: ntpd
        state: restarted
