---
- hosts: all
  
  tasks:
  - name: installing ntp
    yum: 
      name: ntp 
      state: latest
  - name: ensure ntp is running
    service:
      name: ntp
      state: started
  handlers:
    - name: if ntp is not running
      service: 
        name: ntpd 
        state: restarted
